version: '3.8'

services:
  app:
    build: .
    container_name: ci4_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - CI_ENVIRONMENT=development
      - DB_HOST=db.sxlhygcxwwujmdpmzaob.supabase.co
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=Rafie*1987
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: ci4_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Rafie*1987
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
