services:
  app:
    build: .
    container_name: ci4_app
    ports:
      - "8080:80"
    environment:
      - CI_ENVIRONMENT=${CI_ENVIRONMENT}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    volumes:
      - ./writable:/var/www/html/writable
